apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: main
  namespace: monitoring
spec:
  mode: statefulset
  managementState: managed
  targetAllocator:
    enabled: true
    prometheusCR:
      enabled: true
      podMonitorSelector: {}
      serviceMonitorSelector: {}

  config:
    receivers:
      # Scrape prometheus metrics in the collector by using the prometheus-operator CRDs
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 30s
              static_configs:
              - targets: ['0.0.0.0:8888']
        target_allocator:
          endpoint: http://main-targetallocator
          interval: 30s
          collector_id: "${POD_NAME}"

      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    exporters:
      debug:
        verbosity: detailed

      otlp:
        endpoint: "" # TODO: Add proper endpoint
        headers:
          x-scope-orgid: "1"
        tls:
          insecure: true

      prometheus:
        endpoint: "" # TODO: Add proper endpoint

    # TODO: Fill pipelines with correct data
    service:
      pipelines:
        traces:
          receivers: []
          exporters: []
        metrics:
          receivers: []
          exporters: []
