apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jaeger
  name: {{.Release.Name}}-jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - image: jaegertracing/all-in-one:latest
        name: jaeger
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        ports:
        - containerPort: 4317
        - containerPort: 4318
        - containerPort: 16686
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
  name: {{ .Release.Name }}-jaeger
spec:
  ports:
  - name: grpc
    port: 4317
    targetPort: 4317
  - name: http
    port: 4318
    targetPort: 4318
  - name: ui
    port: 16686
    targetPort: 16686
  selector:
    app: jaeger
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
  name: {{ .Release.Name }}-jaeger-node-port
spec:
  type: NodePort
  ports:
  - name: ui
    port: 16686
    targetPort: 16686
  selector:
    app: jaeger